spring:
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/springdatajpa?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1998
    driver-class-name: com.mysql.jdbc.Driver