server:
  port: 9006
spring:
  application:
    name: tensquart_spit
  data:
    mongodb:
      host: 193.112.75.251
      database: spitdb
      port: 27017
  redis:
    host: 193.112.75.251
eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true