server:
  port: 9004
spring:
  application:
    name: tensquare-areicle #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.75.251:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 193.112.75.251
    port: 6379
  data:
    mongodb:
      host: 193.112.75.251
      database: commentdb
      port: 27017
eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
      #租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30